name: Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker version
      run: docker version
    - name: docker info
      run: docker info
    - name: docker build
      run: docker build .

