name: MacOS

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  cmake_make:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check java
      run: java -version
    - name: Check maven
      run: mvn --version
    - name: Install or-tools
      run: |
        wget "https://github.com/google/or-tools/releases/download/v7.7/java_osx.zip";
        unzip java_osx.zip;

