name: MacOS

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check java
      run: java -version
    - name: Check maven
      run: mvn --version
    - name: Install or-tools
      run: |
        mkdir repo
        cd repo
        wget "https://github.com/google/or-tools/releases/download/v8.1/java_osx.zip"
        unzip java_osx.zip
        mvn org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file -Dfile=ortools-java-8.1.8487.jar
        mvn org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file -Dfile=ortools-darwin-8.1.8487.jar
    - name: Compile
      run: mvn compile
    - name: Test
      run: mvn exec:java -Dexec.mainClass="org.mizux.ortools.Test"
