name: MacOS

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check java
      run: java -version
    - name: Check maven
      run: mvn --version
    - name: Install or-tools
      run: |
        mkdir repo;
        cd repo;
        wget "https://github.com/google/or-tools/releases/download/v7.7/java_osx.zip";
        unzip java_osx.zip;
        unzip -j java_osx/ortools-java-7.7.7810.jar META-INF/maven/com.google.ortools/ortools-java/pom.xml;
        mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=java_osx/ortools-java-7.7.7810.jar -DpomFile=pom.xml;
        mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=java_osx/ortools-darwin-7.7.7810.jar;
    - name: Compile
      run: mvn compile
    - name: Test
      run: mvn exec:java -Dexec.mainClass="org.mizux.ortools.Test"
