name: Windows

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check java
      run: java -version
    - name: Check maven
      run: mvn --version
    - name: Download or-tools artifact
      run: |
        new-item -Name repo -ItemType directory
        ls
        cd repo
        (New-Object System.Net.WebClient).DownloadFile("https://github.com/google/or-tools/releases/download/v8.0/java_win.zip","java_win.zip")
        ls
        Expand-Archive .\java_win.zip .
        unzip -j ortools-java-8.0.8283.jar META-INF/maven/com.google.ortools/ortools-java/pom.xml
        mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=ortools-java-7.7.8283.jar -DpomFile=pom.xml
        mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=ortools-win32-x86-64-8.0.8283.jar
    - name: Compile
      run: mvn compile
    - name: Test
      run: mvn exec:java -Dexec.mainClass="org.mizux.ortools.Test"
