name: Windows

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check java
      run: java -version
    - name: Check maven
      run: mvn --version
    - name: Install or-tools
      run: |
        (New-Object System.Net.WebClient).DownloadFile("https://github.com/google/or-tools/releases/download/v7.7/java_win.zip","ortools.zip");
        Expand-Archive .\ortools.zip .;
        mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=java_win/ortools-win32-x86-64-7.7.7810.jar;
        mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=java_win/ortools-java-7.7.7810.jar;
    - name: Compile
      run: mvn compile
    - name: Test
      run: mvn exec:java -Dexec.mainClass="org.mizux.ortools.Test"
